---
title: "Data Exploration"
author: "Matt Emery"
date: "09/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(here)
```

```{r}

options(readr.default_locale=readr::locale(tz="America/Vancouver"))

biological_process <- read_csv(
  here("data/00_raw/labels_BP.csv"),
  col_names = c(
    "gene",
    "bp_validation",
    "bp1",
    "bp2",
    "bp3",
    "bp4",
    "bp5",
    "bp6",
    "bp7",
    "bp8"
    ),
  skip = 1
  )

tidy_bp <- biological_process %>% 
  pivot_longer(-gene, values_drop_na = TRUE) %>% 
  mutate(name = if_else(str_detect(string = .data$name, pattern = "bp\\d"), "bp", .data$name))
```


```{r}
cellular_components <- read_csv(
    here("data", "00_raw","labels_CC.csv"),
  col_names = c(
    "gene",
    "cc_validation",
    "cc1",
    "cc2",
    "cc3",
    "cc4",
    "cc5",
    "cc6",
    "cc7",
    "cc8"
    ),
  skip = 1
  )

tidy_cc <- cellular_components %>% 
  pivot_longer(-gene, values_drop_na = TRUE) %>% 
  mutate(name = if_else(str_detect(string = .data$name, pattern = "cc\\d"), "cc", .data$name))
```

```{r}
molecular_function <- read_csv(here(
  "data", "00_raw", "labels_MF.csv"),
  col_names = c(
    "gene",
    "mf_validation",
    "mf1",
    "mf2",
    "mf3",
    "mf4",
    "mf5",
    "mf6",
    "mf7",
    "mf8"
    ),
  skip = 1
  )

tidy_mf <- molecular_function %>% 
  pivot_longer(-gene, values_drop_na = TRUE) %>% 
  mutate(name = if_else(str_detect(string = .data$name, pattern = "mf\\d"), "mf", .data$name))
```
```{r}
tidy_attributes <- bind_rows(tidy_bp, tidy_cc, tidy_mf)
```

```{r}
conditions_df <- read_csv(here("data", "00_raw", "conditions_annotation.csv")) %>% 
  rename(condition = ID) %>% 
  group_by(.data$condition) %>% 
  mutate(condition_number = row_number())
```

```{r}
tidy_conditions <- conditions_df %>% 
  pivot_longer(cols = c(-condition, -condition_number), values_drop_na = TRUE)
```

```{r}
expressions_df <- read_csv(here("data", "00_raw", "SC_expression.csv"))
```

Looking at duplicate columns


```{r}
tidy_expressions <- expressions_df %>%
  rename(gene = X1) %>% 
  pivot_longer(-gene, names_to = "condition") %>% 
  mutate(
    condition_number = if_else(str_detect(condition, "_1$"), 2, 1),
    condition = str_remove(condition, "_1$")
    )
```

```{r}
write_csv(tidy_expressions, here("data", "tidy_data", "tidy_expressions.csv"))
write_csv(tidy_conditions, here("data", "tidy_data", "tidy_conditions.csv"))
write_csv(tidy_attributes, here("data", "tidy_data", "tidy_attributes.csv"))
```

