---
title: "tidy-tsne"
author: "Casey Engstrom"
date: "20/10/2019"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(Rtsne)
```


all data must be in app/data
```{r}

# make a copy of this into app/data
group_table <- read_csv(here("data/05_grouping_experiments/05_grouping_table"))
write_csv(group_table, "app/data/stain_meta_grouping.csv")


```


```{r}
rel_expr_wide <- rel_expr %>% 
  pivot_wider(names_from = gene_name, values_from = rel_expr)

sample_names_vec <- rel_expr_wide %>% select(culture_treatment) %>% pull()

rel_expr_wide_mat <- rel_expr_wide %>% 
  select(-culture_treatment) %>% 
  as.matrix()



perplex <- 10

tsne_out <- Rtsne(rel_expr_wide_mat,perplexity = perplex, check_duplicates = FALSE)

tsne_out$Y
my_tsne_tibble <- as_tibble(tsne_out$Y)
my_tsne_tibble <- my_tsne_tibble %>% 
  add_column(sample_names_vec, .before=1)



my_tsne_tibble <- my_tsne_tibble %>% 
  left_join(group_table, by=c("sample_names_vec"="ID"))

ggplot(my_tsne_tibble, aes(x=V1, y=V2)) +
  geom_point(aes(color = Group))
```

